apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-app
  template:
    metadata:
      labels:
        app: expense-app
    spec:
      volumes:
        - name: vault-secret
          emptyDir: {}
      initContainers:
        - name: get-secrets
          image: public.ecr.aws/u4j6q5s8/kubernetes-vault-init-container:1.2
          env:
            - name: VAULT_ADDR
              value: https://vault-internal.pdevops72.online:8200
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token
                  key: token
            - name: SECRET_NAME
              value: common/vault
            - name: VAULT_SKIP_VERIFY
              value: "TRUE"
          volumeMounts:
            - name: vault-secret
              mountPath: /data
        - name: schema
          image: public.ecr.aws/u4j6q5s8/backend-schema:1.4
          volumeMounts:
            - name: vault-secret
              mountPath: /data
      containers:
        - name: expense-container
          image: 041445559784.dkr.ecr.us-east-1.amazonaws.com/expense:latest
          volumeMounts:
            - name: vault-secret
              mountPath: /data
