apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
spec:
  selector:
    appName: {{ .Values.component }}
    projectName: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
  type: {{ .Values.type }}



#  ExpenseApp123----DB_PASS
#expense----DB_USER
